-- Water Billing System: executable schema
-- Run against an EMPTY database (e.g. the water-billing-test Supabase project).
-- Order matters: a table must exist before another table's FOREIGN KEY points at it.

CREATE TABLE public.accounts (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  account_number text NOT NULL UNIQUE,
  address text,
  account_type text NOT NULL,
  price_per_unit numeric NOT NULL DEFAULT 120,
  deleted_at timestamptz,
  CONSTRAINT accounts_pkey PRIMARY KEY (id)
);

CREATE TABLE public.people (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  name text NOT NULL,
  phone_number text,
  contact_method varchar DEFAULT 'whatsapp',
  CONSTRAINT people_pkey PRIMARY KEY (id)
);

CREATE TABLE public.account_people (
  account_id integer NOT NULL,
  person_id integer NOT NULL,
  CONSTRAINT account_people_pkey PRIMARY KEY (account_id, person_id),
  CONSTRAINT account_people_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(id),
  CONSTRAINT account_people_person_id_fkey FOREIGN KEY (person_id) REFERENCES public.people(id)
);

CREATE TABLE public.bills (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  account_id integer NOT NULL,
  billing_month integer NOT NULL,
  billing_year integer NOT NULL,
  previous_reading numeric NOT NULL,
  current_reading numeric NOT NULL,
  units_used numeric NOT NULL,
  rate_applied numeric NOT NULL,
  amount_due numeric NOT NULL,
  status text NOT NULL DEFAULT 'unpaid' CHECK (status IN ('unpaid', 'partial', 'paid')),
  opening_balance numeric NOT NULL DEFAULT 0,
  closing_balance numeric NOT NULL DEFAULT 0,
  created_at timestamp NOT NULL DEFAULT now(),
  notified_at timestamp,
  CONSTRAINT bills_pkey PRIMARY KEY (id),
  CONSTRAINT bills_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(id)
);

CREATE TABLE public.payments (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  bill_id integer NOT NULL,
  amount numeric NOT NULL,
  payment_date date NOT NULL,
  CONSTRAINT payments_pkey PRIMARY KEY (id),
  CONSTRAINT payments_bill_id_fkey FOREIGN KEY (bill_id) REFERENCES public.bills(id)
);

CREATE TABLE public.users (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  username text NOT NULL UNIQUE,
  password_hash text NOT NULL,
  role text NOT NULL CHECK (role IN ('owner', 'meter_reader')),
  CONSTRAINT users_pkey PRIMARY KEY (id)
);

CREATE TABLE public.adjustments (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  account_id integer NOT NULL,
  amount numeric NOT NULL,
  reason text,
  created_at timestamp NOT NULL DEFAULT now(),
  CONSTRAINT adjustments_pkey PRIMARY KEY (id),
  CONSTRAINT adjustments_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.accounts(id)
);

CREATE TABLE public.ads (
  id bigint GENERATED ALWAYS AS IDENTITY,
  business_name text NOT NULL,
  description text NOT NULL,
  landmark text,
  phone_number text NOT NULL,
  category text NOT NULL,
  tier text NOT NULL CHECK (tier IN ('starter', 'pro', 'growth')),
  active boolean NOT NULL DEFAULT true,
  click_count integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT ads_pkey PRIMARY KEY (id)
);

CREATE TABLE public.daily_insights (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  insight_date date NOT NULL UNIQUE,
  insight_text text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT daily_insights_pkey PRIMARY KEY (id)
);

CREATE TABLE public.mpesa_transactions (
  id bigint GENERATED ALWAYS AS IDENTITY,
  bill_id bigint NOT NULL,
  checkout_request_id text UNIQUE,
  merchant_request_id text,
  phone_number text NOT NULL,
  amount numeric NOT NULL,
  status text NOT NULL DEFAULT 'pending',
  mpesa_receipt text,
  result_desc text,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT mpesa_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT mpesa_transactions_bill_id_fkey FOREIGN KEY (bill_id) REFERENCES public.bills(id)
);

CREATE VIEW public.latest_bills AS
SELECT DISTINCT ON (account_id) account_id,
    closing_balance,
    billing_year,
    billing_month,
    notified_at
FROM bills
ORDER BY account_id, billing_year DESC, billing_month DESC;